### ISSUE TITLE
RuntimeError: the bucket being iterated changed size

### ISSUE THREAD

**Issue by gogobd** [plone/plone.app.multilingualindexes#3]
I encountered a problem within plone.app.multilingualindexes while using transmogrifier: "RuntimeError: the bucket being iterated changed size". Google quickly brought me to a page where this Error is explained: <http://www.zodb.org/en/latest/articles/old-guide/modules.html> in the paragraph "Iteration and Mutation" we learn that the current code is prone to causing exactly the error I ran into. It recommends: "[…]As with a Python dictionary or list, you should not mutate a BTree-based data structure while iterating over it[…]". Now I changed the code to the solution shown in the example, and it works again. I have no idea if that error could be triggered under "normal circumstances" i.e. by users working with plone, but I need it out of the way. ("Normal circumstances" and "Plone" are orthogonal concepts anyways...)

**Comment by jensens** [comment]
fixed with e271e0eb95ccd7f7a9d3b6d3f4cf64f2ea525a70
