### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by iham** [plone/plone.app.multilingualindexes#8]
i was happy about the release of pami - but then this happened:

```
  File "/Users/me/Sandbox/my.site/eggs/plone.app.multilingualindexes-2.0-py2.7.egg/plone/app/multilingualindexes/languagefallback.py", line 8, in <module>
    from plone.app.multilingual.events import ITranslationRegisteredEvent
```

seems the latest release is relying on code that does not exist in pam for quiet a while.

i'm on
plone master / rc5+
python 2.7
pam 5.3.5

**Comment by jensens** [comment]
Needs Master or ask Eric for a release.
